spring:
  jpa:
    show-sql: true
    
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
logging:
  level:
    org.springframework : debug
    
    